name: CI with Dependency Caching

# Trigger on push, pull request, and manual dispatch
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-with-cache:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js (creates package dependencies to cache)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Create package.json if it doesn't exist (for demo purposes)
      - name: Create demo package.json
        run: |
          if [ ! -f "package.json" ]; then
            cat > package.json << 'EOF'
          {
            "name": "data-science-portfolio",
            "version": "1.0.0",
            "description": "Data Science Portfolio with CI/CD",
            "dependencies": {
              "lodash": "^4.17.21",
              "axios": "^1.6.0",
              "express": "^4.18.2",
              "moment": "^2.29.4"
            },
            "devDependencies": {
              "jest": "^29.7.0",
              "eslint": "^8.55.0"
            },
            "scripts": {
              "test": "echo 'Tests passed!'",
              "build": "echo 'Build completed!'"
            }
          }
          EOF
            echo "✅ Demo package.json created"
          fi

      # Cache dependencies with the specified key
      - name: Cache Node.js dependencies  
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: cache-71f84a5-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: |
            cache-71f84a5-${{ runner.os }}-node-

      # Step with specified name that checks cache hit/miss result
      - name: prime-cache-71f84a5
        run: |
          echo "=== Cache Status Report ==="
          if [ "${{ steps.cache-deps.outputs.cache-hit }}" = "true" ]; then
            echo "✅ CACHE HIT: Dependencies restored from cache"
            echo "Cache Key: cache-71f84a5-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/package.json') }}"
            echo "This run will be faster due to cached dependencies!"
          else
            echo "❌ CACHE MISS: No cache found, will install fresh dependencies"
            echo "Cache Key: cache-71f84a5-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/package.json') }}"
            echo "Next run will be faster once cache is populated!"
          fi
          echo "Cache Hit Result: ${{ steps.cache-deps.outputs.cache-hit }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "=== End Cache Report ==="

      # Install dependencies (only if cache miss)
      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          echo "Installing Node.js dependencies..."
          npm ci --prefer-offline --no-audit
          echo "✅ Dependencies installed successfully"
